"""
Django settings for examc project.

BASE SETTINGS FOR ALL ENV

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from datetime import datetime
from pathlib import Path
import os
from urllib.parse import urlparse

from django.conf import settings
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[1]

# ----- helpers env
def env(key, default=None): return os.getenv(key, default)
def env_bool(key, default="0"): return str(os.getenv(key, default)).lower() in ("1","true","yes","on")
def env_int(key, default="0"):
    try: return int(os.getenv(key, default))
    except (TypeError, ValueError): return int(default)

# Optional: load .env only for local dev (outside Docker)
if os.getenv("DJANGO_DOTENV", "0") == "1" or not os.getenv("SECRET_KEY"):
    load_dotenv(BASE_DIR / ".env.dev", override=False)  # allows manage.py runserver or migrate, ... locally without Compose
else:
    # Otherwise (prod/test) set port forwarding
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SAMESITE = "Lax"

# Version and about information
VERSION_FILE = BASE_DIR / "VERSION"
try:
    APP_VERSION = VERSION_FILE.read_text(encoding="utf-8").strip()
except FileNotFoundError:
    APP_VERSION = "dev"  # valeur par défaut si le fichier manque

APP_NAME = "eXamc"
APP_LICENSE = "Business Source License (non-commercial)"
APP_OWNER = "EPFL - CePro"



# BASIC SECURITY
SECRET_KEY = env("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "1" if os.path.exists(BASE_DIR / ".env.dev") else "0") in ("1","true","yes","on")

ALLOWED_HOSTS = env("ALLOWED_HOSTS", "*").split(",")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",") if CSRF_TRUSTED_ORIGINS else []

# OTHER SECURITY
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", "0" if DEBUG else "1")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", "0" if DEBUG else "1")
CSRF_COOKIE_SECURE    = env_bool("CSRF_COOKIE_SECURE", "0" if DEBUG else "1")
SECURE_HSTS_SECONDS   = 0 if DEBUG else 15768000 #6mois
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Session timeout after 1h of inactivity. Middleware is managing auto-logout on inactivity
SESSION_COOKIE_AGE = 3600 #86400  # seconds
SESSION_SAVE_EVERY_REQUEST = True  # resets timeout on each request
SESSION_ENGINE = 'django.contrib.sessions.backends.db' #This stores sessions in the django_session table, allowing you to check who is still logged in

# MAX UPLOAD SIZE 10MB (default 2.5MB not enough for review)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760


# Application definition

INSTALLED_APPS = [
    'examc_app.apps.ExamcAppConfig',
    'django.contrib.admindocs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'sslserver',
    'constance',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap4',
    'simple_history',
    'import_export',
    'django_summernote',
    'celery',
    'celery_progress',
    'django_celery_beat',
    'maintenance_mode',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'examc_app.middleware.auto_logout.AutoLogoutMiddleware',
]

AUTO_LOGOUT_DELAY = 1800 # seconds

ROOT_URLCONF = 'examc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'docs/build/html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "examc_app.context_processors.maintenance_notice",
                "examc_app.context_processors.app_metadata",
            ],
        },
    },
]


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DATABASE", "examc"),
        "USER": env("MYSQL_USER", "appuser"),
        "PASSWORD": env("MYSQL_PASSWORD", ""),
        "HOST": env("DB_HOST", "db"),    # en local hors Docker: 127.0.0.1
        "PORT": env("DB_PORT", "3306"),
        "OPTIONS": {
            "autocommit": True,
            "charset": "utf8mb4",
        },
        "CONN_MAX_AGE": env_int("DB_CONN_MAX_AGE", "600"),
    }
}

WSGI_APPLICATION = 'examc.wsgi.application'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = env("TZ",'Europe/Zurich')

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get("STATIC_ROOT", "/static")

# Signed files expiration timeout ms
SIGNED_FILES_EXPIRATION_TIMEOUT = 300
SIGNED_FILES_URL = '/protected/'

# Private media root
PRIVATE_MEDIA_ROOT = Path(os.environ.get("PRIVATE_MEDIA_ROOT", "/private_media"))
# If using Nginx X-Accel-Redirect:
PRIVATE_MEDIA_URL = "/_protected/"

SCANS_ROOT = PRIVATE_MEDIA_ROOT / 'scans/'
#SCANS_URL = '/protected/scans/'

# Marked scans folder
MARKED_SCANS_ROOT = PRIVATE_MEDIA_ROOT / 'marked_scans/'
#MARKED_SCANS_URL = '/protected/marked_scans/'

# Autoupload folder
AUTOUPLOAD_ROOT = PRIVATE_MEDIA_ROOT / 'autoupload/'
#AUTOUPLOAD_URL = '/autoupload/'

# Export marked files folder tmp
EXPORT_TMP_ROOT = PRIVATE_MEDIA_ROOT / 'export_tmp/'
#EXPORT_TMP_URL = '/export_tmp/'
SCALE_PDF_TEMPLATE = BASE_DIR / 'templates/res_and_stats/scale_pdf.html'

# pdf catalogs folder
CATALOG_ROOT = PRIVATE_MEDIA_ROOT / 'catalogs/'
#CATALOG_URL = '/catalogs/'

# AMC projects folder
AMC_PROJECTS_ROOT = PRIVATE_MEDIA_ROOT / 'amc_projects/'
AMC_PROJECTS_URL = '/amc_projects/'

# AMC config file
AMC_CONFIG_FILE = AMC_PROJECTS_ROOT / 'config/amc_config.xml'

# Documentation folder
DOCUMENTATION_ROOT = BASE_DIR / 'docs/build/html/'
DOCUMENTATION_URL = '/docs/build/html/'

# NEW ENTRA ID
####################################################
# Authentication settings
####################################################
AUTHENTICATION_BACKENDS = ("examc_app.auth_backend.ExamcOIDCBackend","django.contrib.auth.backends.ModelBackend")
OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET", "")
TENANT_ID = env("TENANT_ID", "")

AUTH_DOMAIN = f"https://login.microsoftonline.com/{TENANT_ID}"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/token"
OIDC_OP_JWKS_ENDPOINT = f"{AUTH_DOMAIN}/discovery/v2.0/keys"
OIDC_OP_USER_ENDPOINT = "https://graph.microsoft.com/oidc/userinfo"
OIDC_RP_SIGN_ALGO = "RS256"
LOGIN_URL = "/oidc/authenticate/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Only use this setting if you want to store the access token in the session
# To use access token to call API
#OIDC_STORE_ACCESS_TOKEN = True

LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/login_form/',
    r'/$',
    r'/$',
    r'^/oidc/.*$',  # All OIDC-related URLs
    r'^/admin/.*$',
    r'^/admin$',
    r'^/static/.*$',
    r'^/media/.*$',

]
LOGIN_REQUIRED_REDIRECT_FIELD_NAME = 'next_url'

# Email configuration
EMAIL_BACKEND = 'examc_app.email_backend.py'

# Pandoc filters
PANDOC_UTILS_DIR = BASE_DIR / 'examc_app/utils/pandoc'

# Rooms plans pathes
ROOMS_PLANS_ROOT = PRIVATE_MEDIA_ROOT / 'rooms_plans'
ROOMS_PLANS_URL = '/rooms_plans/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django_tequila': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Celery & Redis

CELERY_BROKER_URL = env("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", "0")
CELERY_BEAT_SCHEDULER = env("CELERY_BEAT_SCHEDULER", "django_celery_beat.schedulers:DatabaseScheduler")

# Optional configuration (you can tweak toolbar, height, etc.)
SUMMERNOTE_CONFIG = {
    "iframe": True,  # render directly inline; set True to sandbox in iframe
    "summernote": {
        "width": "100%",
        "height": "280px",
        "toolbar": [
            ["style", ["bold", "italic", "underline", "clear"]],
            ["para", ["ul", "ol", "paragraph"]],
            ['table', ['table']],
            ["insert", ["link","picture","math"]],
            ["view", ["fullscreen", "codeview"]],
            ["misc", ["undo", "redo"]],
        ],
        # DO NOT put 'plugins' or 'math' here — they won’t be passed to the iframe.
    },

    # These are injected into the **iframe** document:
    "css": (
        "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css",
    ),
    "js": (
        # order matters a little less, but keep KaTeX before the plugin if the plugin calls it immediately
        "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js",
         f"{settings.STATIC_URL}js/summernote-math.js"
    ),
    "attachment_storage_class": "examc_app.storage.SummernoteSignedPrivateStorage",
    # optional:
    "attachment_require_authentication": True,
}




#MAINTENANCE_MODE = False commented to let constance manage maintenance
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True
MAINTENANCE_MODE_IGNORE_SUPERUSER = True
MAINTENANCE_MODE_STATE_BACKEND = "maintenance_mode.backends.CacheBackend"
MAINTENANCE_MODE_CACHE_NAME = "maintenance_mode"
# MAINTENANCE_MODE_STATE_FILE_PATH = "/tmp/maintenance_mode_state.txt"
MAINTENANCE_MODE_IGNORE_URLS = (
    r"^/oidc/authenticate/?$",   # OIDC start (mozilla-django-oidc default)
    r"^/oidc/callback/?$",       # OIDC callback (mozilla-django-oidc default)
)

### CONSTANCE FOR MAINTENANCE
CONSTANCE_REDIS_URL = env("CONSTANCE_REDIS_CONNECTION", default="redis://redis:6379/0")
parsed = urlparse(CONSTANCE_REDIS_URL)

REDIS_CONNECTION = {
    "host": parsed.hostname or "redis",
    "port": parsed.port or 6379,
    "db": int((parsed.path or "/0").lstrip("/")),
}
CONSTANCE_BACKEND = "constance.backends.redisd.RedisBackend"
CONSTANCE_REDIS_CONNECTION = REDIS_CONNECTION

# Admin widgets/fields for Constance
CONSTANCE_ADDITIONAL_FIELDS = {
    "optional_datetime": [
        "django.forms.SplitDateTimeField",
        {
            "widget": "django.contrib.admin.widgets.AdminSplitDateTime",
            "required": False,  # <-- this makes it allow blank/None
        },
    ],
    "text": ["django.forms.CharField", {"widget": "django.forms.Textarea", "required": False}],
}
# Editable settings shown in Django admin (Config > Constance)
CONSTANCE_CONFIG = {
    # Controls the banner (pre-maintenance heads-up)
    "MAINT_BANNER_ENABLED": (False, "Show pre-maintenance banner", bool),
    "MAINT_BANNER_FROM":   (None, "Start showing banner at (timezone local) YYYY-MM-DD HH:MM", "optional_datetime"),
    "MAINT_MESSAGE":       ("We’ll be undergoing planned maintenance.", "Banner message", "text"),

    # Actual maintenance window; your scheduler will toggle maintenance mode based on these
    "MAINT_START": (None, "Maintenance starts at (timezone local) YYYY-MM-DD HH:MM", "optional_datetime"),
    "MAINT_END":   (None, "Maintenance ends at (timezone local) YYYY-MM-DD HH:MM", "optional_datetime"),
    "MAINT_BYPASS_AUTHENTICATED": (True, "Hide banner for logged-in users", bool),
    "MAINT_BYPASS_STAFF": (True, "Hide banner for staff", bool),

    # Mail server configuration
    "EMAIL_HOST": ("smtp_myhost","smtp server host",str),
    "EMAIL_PORT": (587,"SMTP server port (587 for TLS, 465 for SSL)",int),
    "EMAIL_USE_SSL": (True, "True for SSL, false for TLS", bool),
    "EMAIL_HOST_USER": ("user","server username",str),
    "EMAIL_HOST_PASSWORD": ("","server password",str),
    "DEFAULT_FROM_EMAIL": ("sender email", "Default sender email address", str),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Planned maintenance": (
        "MAINT_MESSAGE",
        "MAINT_BANNER_ENABLED", "MAINT_BANNER_FROM",
        "MAINT_START", "MAINT_END",
        "MAINT_BYPASS_AUTHENTICATED", "MAINT_BYPASS_STAFF",
    ),
    "Mail configuration": (
        "EMAIL_HOST",
        "EMAIL_PORT",
        "EMAIL_USE_SSL",
        "EMAIL_HOST_USER",
        "EMAIL_HOST_PASSWORD",
        "DEFAULT_FROM_EMAIL",
    )
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("DJANGO_CACHE_URL", default="redis://redis:6379/1"),
    },
    "maintenance_mode": {  # dedicated cache for the flag (optional but nice)
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("DJANGO_MAINTENANCE_CACHE_URL", default="redis://redis:6379/2"),
    },
}