"""
Django settings for examc project.

BASE SETTINGS FOR ALL ENV

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[1]

# ----- helpers env
def env(key, default=None): return os.getenv(key, default)
def env_bool(key, default="0"): return str(os.getenv(key, default)).lower() in ("1","true","yes","on")
def env_int(key, default="0"):
    try: return int(os.getenv(key, default))
    except (TypeError, ValueError): return int(default)

# Optional: load .env only for local dev (outside Docker)
if os.getenv("DJANGO_DOTENV", "0") == "1":
    load_dotenv(BASE_DIR / ".env")  # allows manage.py runserver locally without Compose


# BASIC SECURITY
SECRET_KEY = env("SECRET_KEY")
DEBUG = env_bool("DEBUG","0")

ALLOWED_HOSTS = env("ALLOWED_HOSTS", "*").split(",")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",") if CSRF_TRUSTED_ORIGINS else []

# OTHER SECURITY
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", "0" if DEBUG else "1")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", "0" if DEBUG else "1")
CSRF_COOKIE_SECURE    = env_bool("CSRF_COOKIE_SECURE", "0" if DEBUG else "1")
SECURE_HSTS_SECONDS   = 0 if DEBUG else 15768000 #6mois
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Session timeout after 1h of inactivity. Middleware is managing auto-logout on inactivity
SESSION_COOKIE_AGE = 3600 #86400  # seconds
SESSION_SAVE_EVERY_REQUEST = True  # resets timeout on each request
SESSION_ENGINE = 'django.contrib.sessions.backends.db' #This stores sessions in the django_session table, allowing you to check who is still logged in

# MAX UPLOAD SIZE 10MB (default 2.5MB not enough for review)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760


# Application definition

INSTALLED_APPS = [
    'examc_app.apps.ExamcAppConfig',
    'django.contrib.admindocs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'sslserver',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap4',
    'simple_history',
    'import_export',
    'django_ckeditor_5',
    'celery',
    'celery_progress',
    'django_celery_beat',
    'maintenance_mode',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    #'login_required.middleware.LoginRequiredMiddleware',
    'examc_app.middleware.auto_logout.AutoLogoutMiddleware',
]

AUTO_LOGOUT_DELAY = 1800 # seconds

ROOT_URLCONF = 'examc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'docs/build/html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DATABASE", "examc"),
        "USER": env("MYSQL_USER", "appuser"),
        "PASSWORD": env("MYSQL_PASSWORD", ""),
        "HOST": env("DB_HOST", "db"),    # en local hors Docker: 127.0.0.1
        "PORT": env("DB_PORT", "3306"),
        "OPTIONS": {
            "autocommit": True,
            "charset": "utf8mb4",
        },
        "CONN_MAX_AGE": env_int("DB_CONN_MAX_AGE", "600"),
    }
}


WSGI_APPLICATION = 'examc.wsgi.application'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = env("TZ",'Europe/Zurich')

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For maintenance set True
MAINTENANCE_MODE = False
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get("STATIC_ROOT", "/static")

# Signed files expiration timeout ms
SIGNED_FILES_EXPIRATION_TIMEOUT = 300
SIGNED_FILES_URL = '/protected/'

# Private media root
PRIVATE_MEDIA_ROOT = Path(os.environ.get("PRIVATE_MEDIA_ROOT", "/private_media"))
# If using Nginx X-Accel-Redirect:
PRIVATE_MEDIA_URL = "/_protected/"

SCANS_ROOT = PRIVATE_MEDIA_ROOT / 'scans/'
#SCANS_URL = '/protected/scans/'

# Marked scans folder
MARKED_SCANS_ROOT = PRIVATE_MEDIA_ROOT / 'marked_scans/'
#MARKED_SCANS_URL = '/protected/marked_scans/'

# Autoupload folder
AUTOUPLOAD_ROOT = BASE_DIR / 'autoupload/'
#AUTOUPLOAD_URL = '/autoupload/'

# Export marked files folder tmp
EXPORT_TMP_ROOT = BASE_DIR / 'export_tmp/'
#EXPORT_TMP_URL = '/export_tmp/'
SCALE_PDF_TEMPLATE = BASE_DIR / 'templates/res_and_stats/scale_pdf.html'

# pdf catalogs folder
CATALOG_ROOT = BASE_DIR / 'catalogs/'
#CATALOG_URL = '/catalogs/'

# AMC projects folder
AMC_PROJECTS_ROOT = PRIVATE_MEDIA_ROOT / 'amc_projects/'
AMC_PROJECTS_URL = '/amc_projects/'

# AMC config file
AMC_CONFIG_FILE = AMC_PROJECTS_ROOT / 'config/amc_config.xml'

# Documentation folder
DOCUMENTATION_ROOT = BASE_DIR / 'docs/build/html/'
DOCUMENTATION_URL = '/docs/build/html/'

# NEW ENTRA ID
####################################################
# Authentication settings
####################################################
AUTHENTICATION_BACKENDS = ("examc_app.auth_backend.ExamcOIDCBackend","django.contrib.auth.backends.ModelBackend")
OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET", "")
TENANT_ID = env("TENANT_ID", "")

AUTH_DOMAIN = f"https://login.microsoftonline.com/{TENANT_ID}"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/token"
OIDC_OP_JWKS_ENDPOINT = f"{AUTH_DOMAIN}/discovery/v2.0/keys"
OIDC_OP_USER_ENDPOINT = "https://graph.microsoft.com/oidc/userinfo"
OIDC_RP_SIGN_ALGO = "RS256"
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Only use this setting if you want to store the access token in the session
# To use access token to call API
#OIDC_STORE_ACCESS_TOKEN = True

LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/login_form/',
    r'/$',
    r'/$',
    r'^/oidc/.*$',  # All OIDC-related URLs
    r'^/admin/.*$',
    r'^/admin$',
    r'^/static/.*$',
    r'^/media/.*$',

]
LOGIN_REQUIRED_REDIRECT_FIELD_NAME = 'next_url'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.epfl.ch'  # SMTP server host
EMAIL_PORT = 587  # SMTP server port (587 for TLS, 465 for SSL)
EMAIL_USE_TLS = True  # True for TLS, False for SSL
EMAIL_HOST_USER = 'noreply-cepro-exams'  # SMTP server username
EMAIL_HOST_PASSWORD = 'NP!Cpr0_X@2022'  # SMTP server password
EMAIL_USE_SSL = False  # Set to True if using SSL
DEFAULT_FROM_EMAIL = 'noreply-cepro-exams@epfl.ch'  # Default sender email address

# Pandoc filters
PANDOC_UTILS_DIR = BASE_DIR / 'examc_app/utils/pandoc'

# Rooms plans pathes
ROOMS_PLANS_ROOT = BASE_DIR / 'rooms_plans'
ROOMS_PLANS_URL = '/rooms_plans/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django_tequila': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Celery & Redis

CELERY_BROKER_URL = env("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", "0")
CELERY_BEAT_SCHEDULER = env("CELERY_BEAT_SCHEDULER", "django_celery_beat.schedulers:DatabaseScheduler")

## CKEDITOR Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'blockToolbar': [
            'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'fontSize', 'fontColor', 'bold', 'italic', 'underline', 'strikethrough',
                    'code','subscript', 'superscript','|','bulletedList', 'numberedList', '|', 'alignment', 'outdent', 'indent',
                    '|', 'insertImage','insertTable', '|','codeBlock', 'sourceEditing'],
        'image': {
            'toolbar': ['imageStyle:alignLeft','imageStyle:alignRight', 'imageStyle:alignCenter'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'alignment': {
            'options': [ 'left', 'right' ]
        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5', 'class': 'ck-heading_heading5' }
            ]
        },
        'codeBlock':{
            'languages': [
                { 'language': 'latex', 'label': 'LaTeX' }, # The default 'language'.
            ]
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
