# Generated by Django 5.2.4 on 2025-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0002_alter_historicalpagesgroupcomment_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestiongradingschemecheckbox',
            name='adjustment',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='questiongradingschemecheckbox',
            name='adjustment',
            field=models.BooleanField(default=0),
        ),
    ]
