# Generated by Django 5.2.4 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0007_alter_questiongradingschemecheckbox_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AddField(
            model_name='historicalpagesgroupgradingschemecheckedbox',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagesgroupgradingschemecheckedbox',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historicalquestiongradingschemecheckbox',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiongradingschemecheckbox',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
