# Generated by Django 5.2.4 on 2026-04-24 14:35

import django.utils.timezone
from django.db import migrations, models
from django.db.models import Count, Max


def deduplicate_review_locks(apps, schema_editor):
    ReviewLock = apps.get_model('examc_app', 'ReviewLock')

    duplicate_groups = (
        ReviewLock.objects.values('pages_group_id', 'student_id')
        .annotate(lock_count=Count('id'), keep_id=Max('id'))
        .filter(lock_count__gt=1)
    )

    for group in duplicate_groups:
        (
            ReviewLock.objects
            .filter(
                pages_group_id=group['pages_group_id'],
                student_id=group['student_id'],
            )
            .exclude(id=group['keep_id'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0010_historicalpagesgroupstudentreportnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewlock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now=True),
            preserve_default=False,
        ),
        migrations.RunPython(deduplicate_review_locks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reviewlock',
            constraint=models.UniqueConstraint(fields=('pages_group', 'student'), name='uniq_review_lock_pages_group_student'),
        ),
        migrations.AddIndex(
            model_name='reviewlock',
            index=models.Index(fields=['updated_at'], name='review_lock_updated_idx'),
        ),
    ]
