# Generated by Codex on 2026-06-29

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count, Max


def normalize_copy_no(value):
    try:
        return str(int(value))
    except (TypeError, ValueError):
        return str(value or "0")


def populate_review_lock_copy_no(apps, schema_editor):
    ReviewLock = apps.get_model("examc_app", "ReviewLock")

    for lock in ReviewLock.objects.select_related("student"):
        student = getattr(lock, "student", None)
        copy_no = student.copie_no if student else lock.copy_no
        lock.copy_no = normalize_copy_no(copy_no)
        lock.save(update_fields=["copy_no"])


def deduplicate_review_locks_by_copy_no(apps, schema_editor):
    ReviewLock = apps.get_model("examc_app", "ReviewLock")

    duplicate_groups = (
        ReviewLock.objects.values("pages_group_id", "copy_no")
        .annotate(lock_count=Count("id"), keep_id=Max("id"))
        .filter(lock_count__gt=1)
    )

    for group in duplicate_groups:
        (
            ReviewLock.objects
            .filter(
                pages_group_id=group["pages_group_id"],
                copy_no=group["copy_no"],
            )
            .exclude(id=group["keep_id"])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("examc_app", "0012_historicalpagesgroupgradingschemecheckedbox_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewlock",
            name="copy_no",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.RunPython(populate_review_lock_copy_no, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_review_locks_by_copy_no, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="reviewlock",
            name="uniq_review_lock_pages_group_student",
        ),
        migrations.AlterField(
            model_name="reviewlock",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewLocks",
                to="examc_app.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewlock",
            constraint=models.UniqueConstraint(
                fields=("pages_group", "copy_no"),
                name="uniq_review_lock_pages_group_copy",
            ),
        ),
    ]
