import os
from pathlib import Path
from typing import Optional

from examc import settings
from examc_app.models import Exam, PrepQuestion, PrepQuestionAnswer

def get_amc_project_path(exam,even_if_not_exist):
    amc_project_path = str(settings.AMC_PROJECTS_ROOT)+"/"+str(exam.year.code)+"/"+str(exam.semester.code)+"/"+exam.code+"_"+exam.date.strftime("%Y%m%d")

    print('****************** amc_project_path : ' + amc_project_path)
    if os.path.isdir(amc_project_path):
        return amc_project_path
    elif even_if_not_exist:
        return amc_project_path
    else:
        return None

# ---------------------------------------------------------------------------
# AMC ID HELPERS (SINGLE SOURCE OF TRUTH)
# ---------------------------------------------------------------------------

def get_amc_question_id(question: PrepQuestion) -> str:
    """
    Must stay aligned with LaTeX generation.
    Example:
        SECTION-1-SCQ-3
    """
    return (
        f"SECTION-{question.prep_section.position}-"
        f"{question.question_type.code}-{question.position}"
    )


def get_amc_answer_code(
    question: PrepQuestion,
    answer: PrepQuestionAnswer,
) -> str:
    """
    Internal Django-side identifier (not required by AMC itself).
    Example:
        SECTION-1-SCQ-3-A2
    """
    return f"{get_amc_question_id(question)}-A{answer.position}"


# ---------------------------------------------------------------------------
# BUILD / PATH HELPERS
# ---------------------------------------------------------------------------

def get_exam_build_base_path(exam: Exam, base_dir: str) -> Path:
    """
    Root folder for all builds of an exam.
    Example:
        /data/amc/exams/{exam.code}/
    """
    return Path(base_dir) / f"{exam.code}"


def get_exam_build_path(exam: Exam, version: int, base_dir: str) -> Path:
    """
    Path for a specific build version.
    Example:
        /data/amc/exams/MATH101/build_1/
    """
    return get_exam_build_base_path(exam, base_dir) / f"build_{version}"


def get_exam_latex_main_file(build_path: Path) -> Path:
    """
    Main LaTeX file.
    """
    return build_path / "exam.tex"


def get_exam_pdf_path(build_path: Path) -> Path:
    """
    Final compiled PDF.
    """
    return build_path / "amc-compiled.pdf"


def get_amc_log_path(build_path: Path) -> Path:
    """
    AMC log file generated during compilation.
    """
    return build_path / "amc-compiled.amc"


def get_xy_path(build_path: Path) -> Path:
    """
    Layout file generated by AMC.
    """
    return build_path / "calage.xy"


# ---------------------------------------------------------------------------
# SAFETY HELPERS
# ---------------------------------------------------------------------------

def ensure_directory(path: Path) -> None:
    """
    Ensure a directory exists.
    """
    path.mkdir(parents=True, exist_ok=True)


def safe_str(value: Optional[str]) -> str:
    """
    Avoid None issues when serializing/debugging.
    """
    return value or ""