[project]
name = "examc"
version = "2.0.0"
requires-python = "==3.14.*"

dependencies = [
    "asgiref==3.12.1",
    "celery-progress==0.5",
    "celery-types==0.26.0",
    "celery==5.6.3",
    "chardet==7.6.0",
    "crispy-bootstrap4==2026.2",
    "django-celery-beat==2.9.0",
    "django-constance==4.3.5",
    "django-crispy-forms==2.7",
    "django-extensions==4.1",
    "django-import-export==4.4.1",
    "django-maintenance-mode==0.23.0",
    "django-simple-history==3.13.0",
    "django-summernote==0.8.20.0",
    "django-vite>=3.1.0",
    "django==6.0.8",
    "djangorestframework>=3.18.1",
    "docutils==0.21.2",
    "fpdf2==2.8.9",
    "gunicorn==26.2.0",
    "img2pdf==0.6.3",
    "ldap3==2.9.1",  # TODO : replace with more up-to-date python-ldap
    "mozilla-django-oidc==5.0.2",
    "mysqlclient==2.3.0",
    "num2words==0.5.14",
    "numpy==2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "openpyxl==3.1.5",
    "pandas==3.0.6",
    "pandocfilters==1.5.1",
    "pillow==12.3.0",
    "pypandoc==1.17",
    "pypdf==6.19.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.3",
    "pytz==2026.4",
    "pyzbar==0.1.9",
    "redis==8.1.0",
    "reportlab==5.0.1",
    "scipy==1.18.1",
    "shapely==2.1.2",
    "unidecode==1.4.0",
    "xmltodict==1.0.4",
]

[dependency-groups]
test = [
    "bandit==1.9.4",
    "pip-audit==2.10.1",
    "pytest-django==4.14.0",
    "pytest==9.1.1"
]

dev = [
    "deptry==0.25.1"
]

docs = [
    "furo==2025.12.19",
    "sphinx-autobuild==2025.8.25",
    "sphinx==8.2.3"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["examc*"]
exclude = [
    "templates*"
]

[tool.deptry.per_rule_ignores]
DEP002 = [
    # Used in production
    "gunicorn",

    # Django-related, not directly imported
    "asgiref",
    "celery-types",
    "crispy-bootstrap4",
    "django-celery-beat",
    "django-crispy-forms",
    "django-extensions",
    "django-vite",
    "mysqlclient",
    "redis",

    # Sphinx-related, project is in directory ./docs/
    "furo",
    "sphinx"
]

[tool.uv]
exclude-newer = "7 days"
