from django.contrib.staticfiles.storage import ManifestStaticFilesStorage


class ExcludeVitePathsManifestStorage(ManifestStaticFilesStorage):
    """
    Custom storage class for static files that excludes specific files starting with
    "vite/" from Django's default manifest processing and hashing behavior.

    This class is designed to handle scenarios where certain static files (e.g., those
    generated by Vite.js or similar frontend tools) should not be hashed or processed
    by Django, allowing them to remain untouched while other static files are processed
    as usual.
    """
    def url(self, name: str, force: bool = False):
        if name.startswith("vite/"):
            return f"{self.base_url}{name}"
        return super().url(name, force)

    def hashed_name(self, name, content=None, filename=None):
        if name.startswith("vite/"):
            return name
        return super().hashed_name(name, content, filename)

    def post_process(self, paths, dry_run=False, **options):
        vite_paths = {k: v for k, v in paths.items() if k.startswith("vite/")}
        other_paths = {k: v for k, v in paths.items() if not k.startswith("vite/")}

        # Let Django hash/process everything except vite/ as normal
        yield from super().post_process(other_paths, dry_run, **options)

        # Pass vite/ files through untouched, still reporting them as processed
        for name, (storage, path) in vite_paths.items():
            yield name, name, False