# Generated by Django 5.2.4 on 2025-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpagesgroupcomment',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='correct_answer',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pagesgroupcomment',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
