# Generated by Django 5.2.4 on 2025-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0003_historicalquestiongradingschemecheckbox_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='first_page_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='first_page_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
