# Generated by Django 5.2.4 on 2025-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0005_question_uniq_question_exam_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='removed_from_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='removed_from_common',
            field=models.BooleanField(default=False),
        ),
    ]
