# Generated by Django 5.2.4 on 2026-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0008_remove_historicalquestion_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpagesgroupgradingschemecheckedbox',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='pagesgroupgradingschemecheckedbox',
            name='comment',
        ),
    ]
