# Generated by Django 5.2.4 on 2026-07-01 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0013_reviewlock_copy_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrecognizedReviewScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('upload_order', models.PositiveIntegerField()),
                ('previous_copy_no', models.CharField(blank=True, max_length=10)),
                ('previous_page_no', models.CharField(blank=True, max_length=10)),
                ('previous_relative_path', models.CharField(blank=True, max_length=500)),
                ('next_copy_no', models.CharField(blank=True, max_length=10)),
                ('next_page_no', models.CharField(blank=True, max_length=10)),
                ('next_relative_path', models.CharField(blank=True, max_length=500)),
                ('assigned_copy_no', models.CharField(blank=True, max_length=10)),
                ('assigned_page_no', models.CharField(blank=True, max_length=10)),
                ('assigned_mode', models.CharField(blank=True, choices=[('normal', 'Normal page'), ('extra', 'Extra page')], max_length=10)),
                ('assigned_relative_path', models.CharField(blank=True, max_length=500)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unrecognized_review_scans', to='examc_app.exam')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unrecognized_review_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_id', 'upload_order', 'id'],
            },
        ),
    ]
