# Generated by Django 5.2.17 on 2026-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0015_unrecognizedreviewscan_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpagesgroup',
            name='grading_help',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pagesgroup',
            name='grading_help',
            field=models.TextField(blank=True, default=''),
        ),
    ]
