# Generated by Django 5.2.17 on 2026-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0016_alter_historicalpagesgroup_grading_help_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestiongradingscheme',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiongradingscheme',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]