# Generated by Django 5.2.17 on 2026-09-29 07:53

from django.db import migrations, models


def box_type_null_strings_to_null(apps, schema_editor):
    # Points of open questions were stored with the string "null" (old default) or ""
    PrepQuestionAnswer = apps.get_model('examc_app', 'PrepQuestionAnswer')
    PrepQuestionAnswer.objects.filter(box_type__in=["null", ""]).update(box_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0018_preparation_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('0.5', '0.5'), ('1', '1')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('0.5', '0.5'), ('1', '1')], default='1', max_length=10, null=True),
        ),
        migrations.RunPython(box_type_null_strings_to_null, migrations.RunPython.noop),
    ]
