# Generated by Django 5.2.17 on 2026-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0020_prepstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprepstudent',
            name='needs_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepstudent',
            name='needs_correction',
            field=models.BooleanField(default=False),
        ),
    ]
