# Generated by Django 6.0.8 on 2026-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0021_prepstudent_needs_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='unrecognizedreviewscan',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
