# Generated by Django 4.2.5 on 2023-10-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.CharField(max_length=9)),
                ('present_students', models.IntegerField(default=0)),
                ('pdf_catalog_name', models.CharField(blank=True, max_length=100)),
                ('overall', models.BooleanField(default=0)),
                ('indiv_formula', models.CharField(blank=True, max_length=100)),
                ('pages_by_copy', models.IntegerField(blank=True, default=0)),
                ('common_exams', models.ManyToManyField(blank=True, to='examreview_app.exam')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-semester', 'code'],
                'unique_together': {('code', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExamPagesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='0', max_length=20)),
                ('page_from', models.IntegerField(default=0)),
                ('page_to', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroup', to='examreview_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ScanMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copie_no', models.CharField(default='0', max_length=10)),
                ('page_no', models.CharField(default='0', max_length=10)),
                ('filename', models.CharField(max_length=100)),
                ('markers', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanMarkers', to='examreview_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReviewers', to='examreview_app.exam')),
                ('pages_groups', models.ManyToManyField(to='examreview_app.exampagesgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
