# Generated by Django 4.2.5 on 2023-10-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examreview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreviewer',
            name='pages_groups',
            field=models.ManyToManyField(blank=True, to='examreview_app.exampagesgroup'),
        ),
        migrations.CreateModel(
            name='ExamPagesGroupComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
                ('is_new', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupComments', to='examreview_app.exam')),
                ('pages_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupComments', to='examreview_app.exampagesgroup')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrenComments', to='examreview_app.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
