# Generated by Django 4.2.5 on 2024-02-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanmarkers',
            name='pages_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupMarkers', to='examreview_app.exampagesgroup'),
        ),
    ]
