# Generated by Django 3.2.9 on 2022-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pages_by_copy',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
