# Generated by Django 4.2.5 on 2023-10-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0002_alter_examreviewer_pages_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampagesgroupcomments',
            name='exam',
        ),
    ]
