# Generated by Django 3.2.9 on 2022-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0003_alter_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='pages_by_copy',
        ),
        migrations.AddField(
            model_name='exam',
            name='common_exams',
            field=models.ManyToManyField(blank=True, related_name='_examreview_app_exam_common_exams_+', to='examreview_app.Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='indiv_formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='overall',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_catalog_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='present_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
