# Generated by Django 4.2.5 on 2023-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0003_remove_exampagesgroupcomments_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampagesgroupcomments',
            name='copy_no',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
