# Generated by Django 4.2.5 on 2023-10-30 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examreview_app', '0004_exampagesgroupcomments_copy_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPagesGroupComments',
            new_name='ExamPagesGroupComment',
        ),
    ]
