# Generated by Django 3.2.9 on 2022-11-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0004_auto_20221027_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copie_no', models.CharField(default='0', max_length=10)),
                ('filename', models.CharField(max_length=100)),
                ('markers', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scansMarkers', to='examreview_app.exam')),
            ],
        ),
    ]
