# Generated by Django 4.2.5 on 2023-11-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0005_rename_exampagesgroupcomments_exampagesgroupcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampagesgroupcomment',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='examreview_app.exampagesgroupcomment'),
        ),
    ]
