# Generated by Django 3.2.9 on 2022-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0005_scanmarkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanmarkers',
            name='markers',
            field=models.TextField(blank=True),
        ),
    ]
