# Generated by Django 3.2.9 on 2022-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0006_alter_scanmarkers_markers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pages_by_copy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanmarkers',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
