# Generated by Django 4.2.5 on 2023-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0006_alter_exampagesgroupcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampagesgroup',
            name='grading_help',
            field=models.TextField(default=''),
        ),
    ]
