# Generated by Django 4.2.5 on 2023-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0007_exampagesgroup_grading_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pages_by_copy',
            field=models.TextField(blank=True),
        ),
    ]
