# Generated by Django 3.2.9 on 2022-12-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0007_auto_20221214_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanmarkers',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanMarkers', to='examreview_app.exam'),
        ),
        migrations.CreateModel(
            name='ExamPagesGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='0', max_length=20)),
                ('page_from', models.IntegerField(default=0)),
                ('page_to', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroups', to='examreview_app.exam')),
            ],
        ),
    ]
