# Generated by Django 4.2.5 on 2024-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0008_alter_exam_pages_by_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampagesgroup',
            name='correctorBoxes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanmarkers',
            name='correctorBoxMarked',
            field=models.BooleanField(default=False),
        ),
    ]
