# Generated by Django 3.2.9 on 2023-01-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0008_auto_20221220_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPagesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='0', max_length=20)),
                ('page_from', models.IntegerField(default=0)),
                ('page_to', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroup', to='examreview_app.exam')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamPagesGroups',
        ),
    ]
