# Generated by Django 3.2.9 on 2023-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0009_auto_20230110_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pages_by_copy',
            field=models.TextField(blank=True),
        ),
    ]
