# Generated by Django 3.2.9 on 2023-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examreview_app', '0010_alter_exam_pages_by_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanmarkers',
            name='page_no',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
