# Generated by Django 4.2.5 on 2024-02-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.CharField(max_length=9)),
                ('present_students', models.IntegerField(default=0)),
                ('pdf_catalog_name', models.CharField(blank=True, max_length=100)),
                ('overall', models.BooleanField(default=0)),
                ('indiv_formula', models.CharField(blank=True, max_length=100)),
                ('pages_by_copy', models.CharField(blank=True, max_length=10000)),
                ('common_exams', models.ManyToManyField(blank=True, to='examc_app.exam')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-semester', 'code'],
                'unique_together': {('code', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExamPagesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='0', max_length=20)),
                ('page_from', models.IntegerField(default=0)),
                ('page_to', models.IntegerField(default=0)),
                ('grading_help', models.TextField(default='')),
                ('correctorBoxes', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroup', to='examc_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ScanMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copie_no', models.CharField(default='0', max_length=10)),
                ('page_no', models.CharField(default='0', max_length=10)),
                ('filename', models.CharField(max_length=100)),
                ('markers', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('correctorBoxMarked', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanMarkers', to='examc_app.exam')),
                ('pages_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupMarkers', to='examc_app.exampagesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExamReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReviewers', to='examc_app.exam')),
                ('pages_groups', models.ManyToManyField(blank=True, to='examc_app.exampagesgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPagesGroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_no', models.CharField(default='0', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
                ('is_new', models.BooleanField()),
                ('pages_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupComments', to='examc_app.exampagesgroup')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='examc_app.exampagesgroupcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examPagesGroupComments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
