# Generated by Django 4.2.6 on 2024-09-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpagemarkers',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='pagemarkers',
            name='comment',
        ),
        migrations.AlterField(
            model_name='pagesgroupcomment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='examc_app.pagesgroupcomment'),
        ),
    ]
