# Generated by Django 4.2.6 on 2024-09-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0013_historicaluser'),
        ('examc_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('teachers', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(null=True)),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('header_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ExamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExamSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('section_number', models.IntegerField(null=True)),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('header_text', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical exam section',
                'verbose_name_plural': 'historical exam sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExamUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical exam user',
                'verbose_name_plural': 'historical exam users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuestionAnswer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('answer_text', models.TextField(blank=True, default='', null=True)),
                ('formula', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical question answer',
                'verbose_name_plural': 'historical question answers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuestionType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(blank=True, max_length=100)),
                ('formula', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical question type',
                'verbose_name_plural': 'historical question types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalScoringStrategy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('max_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('inv_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('correct_choice_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('wrong_choice_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('no_answer_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('formula', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical scoring strategy',
                'verbose_name_plural': 'historical scoring strategys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PageMarkersUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('answer_text', models.TextField(blank=True, default='', null=True)),
                ('formula', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(blank=True, max_length=100)),
                ('formula', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('inv_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('correct_choice_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('wrong_choice_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('no_answer_points', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('formula', models.TextField(default='')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_strategy', to='examc_app.questionanswer')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='pages_groups',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='users',
        ),
        migrations.RemoveField(
            model_name='historicalpagesgroup',
            name='correctorBoxes',
        ),
        migrations.RemoveField(
            model_name='historicalpagesgroup',
            name='rectangle',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='pagesgroup',
            name='correctorBoxes',
        ),
        migrations.RemoveField(
            model_name='pagesgroup',
            name='rectangle',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qtype',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='first_page_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_catalog_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='prep_option',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='first_page_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='pdf_catalog_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='prep_option',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='formula',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='nb_answers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='question_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='formula',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='nb_answers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='indiv_formula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pages_by_copy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='indiv_formula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='pages_by_copy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpagemarkers',
            name='copie_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpagemarkers',
            name='page_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pagemarkers',
            name='copie_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagemarkers',
            name='page_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalReviewer',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='scoringstrategy',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_strategy', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='scoringstrategy',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_strategy', to='examc_app.question'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examc_app.question'),
        ),
        migrations.AddField(
            model_name='pagemarkersuser',
            name='pageMarkers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageMarkers_users', to='examc_app.pagemarkers'),
        ),
        migrations.AddField(
            model_name='pagemarkersuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pageMarkers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscoringstrategy',
            name='answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.questionanswer'),
        ),
        migrations.AddField(
            model_name='historicalscoringstrategy',
            name='exam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='historicalscoringstrategy',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscoringstrategy',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.question'),
        ),
        migrations.AddField(
            model_name='historicalquestionanswer',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.question'),
        ),
        migrations.AddField(
            model_name='historicalexamuser',
            name='exam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='historicalexamuser',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='historicalexamuser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexamuser',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexamsection',
            name='exam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='historicalexamsection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examuser',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_users', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='examuser',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='examuser',
            name='pages_groups',
            field=models.ManyToManyField(blank=True, to='examc_app.pagesgroup'),
        ),
        migrations.AddField(
            model_name='examuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='examc_app.exam'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='examc_app.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='examc_app.academicyear'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='question_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.questiontype'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.examsection'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examc_app.questiontype'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examc_app.examsection'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='examc_app.semester'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='examc_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='semester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.semester'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.academicyear'),
        ),
    ]
