# Generated by Django 5.2.4 on 2025-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0004_alter_exam_first_page_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'code'), name='uniq_question_exam_code'),
        ),
        migrations.AddConstraint(
            model_name='scale',
            constraint=models.UniqueConstraint(fields=('exam', 'name'), name='uniq_scale_name_per_exam'),
        ),
    ]
