# Generated by Django 5.2.4 on 2026-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0006_historicalquestion_removed_from_common_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongradingschemecheckbox',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='historicalquestiongradingschemecheckbox',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiongradingschemecheckbox',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
