# Generated by Django 5.2.4 on 2026-03-06 12:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0007_alter_questiongradingschemecheckbox_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalexamsection',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='historicalexamsection',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='historicalquestiongradingschemecheckbox',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiongradingschemecheckbox',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='HistoricalPrepSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('section_text', models.TextField(default='')),
                ('position', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exam')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical prep section',
                'verbose_name_plural': 'historical prep sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PrepQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('question_text', models.TextField(default='')),
                ('position', models.IntegerField(default=0)),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepQuestions', to='examc_app.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrepQuestionAnswer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('answer_text', models.TextField(default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prep_question', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.prepquestion')),
            ],
            options={
                'verbose_name': 'historical prep question answer',
                'verbose_name_plural': 'historical prep question answers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PrepQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('answer_text', models.TextField(default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('prep_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepAnswers', to='examc_app.prepquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PrepSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('section_text', models.TextField(default='')),
                ('position', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepSections', to='examc_app.exam')),
            ],
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='prep_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepQuestions', to='examc_app.prepsection'),
        ),
        migrations.CreateModel(
            name='HistoricalPrepQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('question_text', models.TextField(default='')),
                ('position', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.questiontype')),
                ('prep_section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.prepsection')),
            ],
            options={
                'verbose_name': 'historical prep question',
                'verbose_name_plural': 'historical prep questions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='ExamSection',
        ),
        migrations.DeleteModel(
            name='HistoricalExamSection',
        ),
    ]
