# Generated by Django 5.2.4 on 2026-03-11 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0008_remove_historicalquestion_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprepquestion',
            name='fix_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalprepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('50', '0.5'), ('100', '1')], default='grid', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalprepquestion',
            name='scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalprepquestionanswer',
            name='box_height_mm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalprepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('line', 'Line'), ('blank', 'Blank')], default='grid', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalprepquestionanswer',
            name='fix_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprepquestionanswer',
            name='scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalprepsection',
            name='random_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='fix_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('50', '0.5'), ('100', '1')], default='grid', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prepquestionanswer',
            name='box_height_mm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('line', 'Line'), ('blank', 'Blank')], default='grid', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prepquestionanswer',
            name='fix_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepquestionanswer',
            name='scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prepsection',
            name='random_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrepScaleFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepExamScaleFormulas', to='examc_app.exam')),
                ('prep_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepAnswersScaleFormulas', to='examc_app.prepquestionanswer')),
                ('prep_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepQuestionScaleFormulas', to='examc_app.prepquestion')),
                ('prep_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepSectionScaleFormulas', to='examc_app.prepsection')),
            ],
        ),
    ]
