# Generated by Django 5.2.4 on 2026-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0010_historicalprepscaleformula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprepquestion',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='historicalprepquestionanswer',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='prepquestion',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='prepquestionanswer',
            name='scale',
        ),
        migrations.AddField(
            model_name='historicalprepquestion',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
