# Generated by Django 5.2.4 on 2026-03-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0011_remove_historicalprepquestion_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprepscaleformula',
            name='question_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.questiontype'),
        ),
        migrations.AddField(
            model_name='prepscaleformula',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepScaleFormulas', to='examc_app.questiontype'),
        ),
    ]
