# Generated by Django 5.2.4 on 2026-03-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0012_historicalprepscaleformula_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepscaleformula',
            name='prep_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepAnswersScaleFormulas', to='examc_app.prepquestionanswer'),
        ),
        migrations.AlterField(
            model_name='prepscaleformula',
            name='prep_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepQuestionScaleFormulas', to='examc_app.prepquestion'),
        ),
        migrations.AlterField(
            model_name='prepscaleformula',
            name='prep_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepSectionScaleFormulas', to='examc_app.prepsection'),
        ),
    ]
