# Generated by Django 5.2.4 on 2026-03-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0013_alter_prepscaleformula_prep_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPrepScaleFormula',
            new_name='HistoricalPrepScoringFormula',
        ),
        migrations.AlterModelOptions(
            name='historicalprepscoringformula',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical prep scoring formula', 'verbose_name_plural': 'historical prep scoring formulas'},
        ),
        migrations.CreateModel(
            name='PrepScoringFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepExamScoringFormulas', to='examc_app.exam')),
                ('prep_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepAnswersScoringFormulas', to='examc_app.prepquestionanswer')),
                ('prep_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepQuestionScoringFormulas', to='examc_app.prepquestion')),
                ('prep_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepSectionScoringFormulas', to='examc_app.prepsection')),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepScoringFormulas', to='examc_app.questiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='PrepScaleFormula',
        ),
    ]
