# Generated by Django 5.2.4 on 2026-03-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0014_rename_historicalprepscaleformula_historicalprepscoringformula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprepquestion',
            old_name='fix_answers',
            new_name='random_answers',
        ),
        migrations.RenameField(
            model_name='prepquestion',
            old_name='fix_answers',
            new_name='random_answers',
        ),
        migrations.RemoveField(
            model_name='historicalprepquestion',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='prepquestion',
            name='max_points',
        ),
    ]
