# Generated by Django 5.2.4 on 2026-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0015_rename_fix_answers_historicalprepquestion_random_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
