# Generated by Django 5.2.4 on 2026-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0016_historicalprepquestion_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prepquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
