# Generated by Django 5.2.4 on 2026-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0017_alter_historicalprepquestion_max_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('0.5', '0.5'), ('1', '1')], default='grid', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprepquestionanswer',
            name='answer_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalprepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default='grid', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepquestion',
            name='point_increment',
            field=models.CharField(blank=True, choices=[('0.5', '0.5'), ('1', '1')], default='grid', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepquestionanswer',
            name='answer_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default='grid', max_length=10, null=True),
        ),
    ]
