# Generated by Django 5.2.4 on 2026-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0018_exam_duration_historicalexam_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprepquestion',
            name='new_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepquestion',
            name='new_page',
            field=models.BooleanField(default=False),
        ),
    ]
