# Generated by Django 5.2.4 on 2026-04-13 12:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0020_exampreviewjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, default='', max_length=128)),
                ('latex_engine', models.CharField(blank=True, default='pdflatex', max_length=100)),
                ('build_log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('project_path', models.TextField(blank=True, default='')),
                ('latex_main_path', models.TextField(blank=True, default='')),
                ('compiled_pdf_path', models.TextField(blank=True, default='')),
                ('amc_log_path', models.TextField(blank=True, default='')),
                ('xy_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='examc_app.exam')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_exam_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamBuildQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_id', models.CharField(max_length=100)),
                ('rendered_code', models.CharField(blank=True, default='', max_length=150)),
                ('rendered_position', models.PositiveIntegerField()),
                ('section_position', models.PositiveIntegerField(default=1)),
                ('question_type_code', models.CharField(max_length=20)),
                ('prep_question_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=500)),
                ('text_snapshot', models.TextField(blank=True, default='')),
                ('max_points_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('point_increment_snapshot', models.CharField(blank=True, default='', max_length=10)),
                ('random_answers_snapshot', models.BooleanField(default=False)),
                ('new_page_snapshot', models.BooleanField(default=False)),
                ('canceled_snapshot', models.BooleanField(default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_questions', to='examc_app.exambuild')),
                ('prep_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_build_questions', to='examc_app.prepquestion')),
            ],
            options={
                'ordering': ['section_position', 'rendered_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamBuildAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_answer_number', models.PositiveIntegerField()),
                ('rendered_code', models.CharField(blank=True, default='', max_length=150)),
                ('rendered_position', models.PositiveIntegerField()),
                ('prep_answer_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=500)),
                ('answer_text_snapshot', models.TextField(blank=True, default='')),
                ('is_correct_snapshot', models.BooleanField(default=False)),
                ('box_type_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('box_height_mm_snapshot', models.IntegerField(blank=True, null=True)),
                ('fix_position_snapshot', models.BooleanField(default=False)),
                ('prep_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_build_answers', to='examc_app.prepquestionanswer')),
                ('build_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_answers', to='examc_app.exambuildquestion')),
            ],
            options={
                'ordering': ['rendered_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField()),
                ('candidate_code', models.CharField(blank=True, default='', max_length=100)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('scanned', 'Scanned'), ('captured', 'Captured'), ('graded', 'Graded'), ('error', 'Error')], default='generated', max_length=20)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='examc_app.exambuild')),
            ],
            options={
                'ordering': ['copy_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExamBuild',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, default='', max_length=128)),
                ('latex_engine', models.CharField(blank=True, default='pdflatex', max_length=100)),
                ('build_log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('project_path', models.TextField(blank=True, default='')),
                ('latex_main_path', models.TextField(blank=True, default='')),
                ('compiled_pdf_path', models.TextField(blank=True, default='')),
                ('amc_log_path', models.TextField(blank=True, default='')),
                ('xy_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exam')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical exam build',
                'verbose_name_plural': 'historical exam builds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LayoutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField()),
                ('checksum', models.BigIntegerField(blank=True, null=True)),
                ('source_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('dpi', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('mark_diameter', models.FloatField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_pages', to='examc_app.exambuild')),
            ],
            options={
                'ordering': ['copy_number', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner', models.PositiveSmallIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examc_app.layoutpage')),
            ],
            options={
                'ordering': ['corner', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.PositiveIntegerField()),
                ('digit_id', models.PositiveIntegerField()),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digits', to='examc_app.layoutpage')),
            ],
            options={
                'ordering': ['number_id', 'digit_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('answer', 'Answer'), ('question_only', 'Question only'), ('score', 'Score'), ('score_question', 'Score question'), ('question_text', 'Question text'), ('answer_text', 'Answer text'), ('open_grid', 'Open grid'), ('open_box', 'Open box')], default='answer', max_length=30)),
                ('answer_number', models.PositiveIntegerField(default=0)),
                ('flags', models.PositiveIntegerField(default=0)),
                ('char', models.CharField(blank=True, default='', max_length=20)),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('build_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_boxes', to='examc_app.exambuildanswer')),
                ('build_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_boxes', to='examc_app.exambuildquestion')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='examc_app.layoutpage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('namefield', 'Name field'), ('idzone', 'ID zone'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('zone_code', models.CharField(blank=True, default='', max_length=100)),
                ('flags', models.PositiveIntegerField(default=0)),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='examc_app.layoutpage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.TextField(blank=True, default='')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('detected_dpi', models.FloatField(blank=True, null=True)),
                ('rotation_deg', models.FloatField(blank=True, null=True)),
                ('shift_x', models.FloatField(blank=True, null=True)),
                ('shift_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_pages', to='examc_app.exambuild')),
                ('exam_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_pages', to='examc_app.examcopy')),
                ('layout_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_pages', to='examc_app.layoutpage')),
            ],
            options={
                'ordering': ['build_id', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaptureBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_ratio', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_ticked', models.BooleanField(default=False)),
                ('manually_overridden', models.BooleanField(default=False)),
                ('override_value', models.BooleanField(blank=True, null=True)),
                ('layout_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='examc_app.layoutbox')),
                ('scan_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_boxes', to='examc_app.scanpage')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.JSONField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='examc_app.exambuild')),
                ('build_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='examc_app.exambuildquestion')),
                ('exam_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='examc_app.examcopy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exambuild',
            constraint=models.UniqueConstraint(fields=('exam', 'version'), name='exam_build_exam_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exambuildquestion',
            constraint=models.UniqueConstraint(fields=('build', 'rendered_id'), name='build_question_rendered_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exambuildquestion',
            constraint=models.UniqueConstraint(fields=('build', 'rendered_position', 'section_position'), name='build_question_section_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exambuildanswer',
            constraint=models.UniqueConstraint(fields=('build_question', 'rendered_answer_number'), name='build_answer_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='examcopy',
            constraint=models.UniqueConstraint(fields=('build', 'copy_number'), name='exam_copy_build_copy_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='layoutpage',
            constraint=models.UniqueConstraint(fields=('build', 'copy_number', 'page_number'), name='layout_page_build_copy_page_uniq'),
        ),
        migrations.AddConstraint(
            model_name='layoutmark',
            constraint=models.UniqueConstraint(fields=('page', 'corner'), name='layout_mark_page_corner_uniq'),
        ),
        migrations.AddConstraint(
            model_name='layoutdigit',
            constraint=models.UniqueConstraint(fields=('page', 'number_id', 'digit_id'), name='layout_digit_page_number_digit_uniq'),
        ),
        migrations.AddIndex(
            model_name='layoutbox',
            index=models.Index(fields=['page', 'role'], name='examc_app_l_page_id_bfaa69_idx'),
        ),
        migrations.AddIndex(
            model_name='layoutbox',
            index=models.Index(fields=['build_question', 'build_answer'], name='examc_app_l_build_q_cec850_idx'),
        ),
        migrations.AddIndex(
            model_name='layoutzone',
            index=models.Index(fields=['page', 'zone_type'], name='examc_app_l_page_id_16a677_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpage',
            index=models.Index(fields=['build', 'status'], name='examc_app_s_build_i_ed6fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpage',
            index=models.Index(fields=['exam_copy', 'page_number'], name='examc_app_s_exam_co_c9baf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='capturebox',
            constraint=models.UniqueConstraint(fields=('scan_page', 'layout_box'), name='capture_box_scan_layout_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoreresult',
            constraint=models.UniqueConstraint(fields=('build', 'exam_copy', 'build_question'), name='score_result_build_copy_question_uniq'),
        ),
    ]
