# Generated by Django 5.2.4 on 2026-04-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0022_examamcjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='examamcjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='exam_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='examc_app.exambuild'),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='job_type',
            field=models.CharField(choices=[('preview', 'Preview'), ('final_build', 'Final build'), ('layout_extract', 'Layout extraction'), ('scoring_extract', 'Scoring extraction'), ('data_capture', 'Data capture')], default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='pdf_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='result_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExamPreviewJob',
        ),
    ]
