# Generated by Django 5.2.4 on 2026-04-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0023_examamcjob_celery_task_id_examamcjob_exam_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='finalized_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_for_exams', to='examc_app.exambuild'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='finalized_build',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='examc_app.exambuild'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
