# Generated by Django 5.2.4 on 2026-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0024_exam_finalized_at_exam_finalized_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambuildquestion',
            name='amc_question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
