# Generated by Django 5.2.4 on 2026-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0025_exambuildquestion_amc_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default='null', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepquestionanswer',
            name='box_type',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('blank', 'Blank')], default='null', max_length=10, null=True),
        ),
    ]
