# Generated by Django 5.2.4 on 2026-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0026_alter_historicalprepquestionanswer_box_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examamcjob',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examamcjob',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
