# Generated by Django 5.2.4 on 2026-05-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examc_app', '0011_reviewlock_timeout_and_uniqueness'),
        ('examc_app', '0027_examamcjob_progress_current_and_more'),
    ]

    operations = [
    ]
