name: examc-dev

services:
  mysql:
    extends:
      service: mysql
      file: base.yml
    profiles: [ "mysql-dockerized" ] # used to run MySQL outside Docker
    ports:
      - ${DB_PORT:-3307}:3306 # used for local client
    env_file:
      - ../.env.dev
    volumes:
      - ../deploy/db/dev-seed.sql.gz:/docker-entrypoint-initdb.d/20-seed.sql.gz:ro

  redis:
    extends:
      service: redis
      file: base.yml

  nginx:
    extends:
      service: nginx
      file: base.yml
    volumes:
      - ../deploy/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ../data/private_media:/private_media:ro
    ports:
      - "8000:80"

  web:
    extends:
      service: web
      file: base.yml
    build:
      target: tooling
    user: "0"
    environment:
      DEBUG: "1"
      COLLECTSTATIC: "0" # in dev, OK
      PRIVATE_MEDIA_ROOT: /private_media
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - ../app/:/app:z
      - ../data/private_media:/private_media
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload", "--nothreading"]
    env_file:
      - ../.env.dev

  celery:
    extends:
      service: celery
      file: base.yml
    volumes:
      - ../data/private_media:/private_media

  celery_beat:
    extends:
      service: celery_beat
      file: base.yml
    volumes:
      - ../data/private_media:/private_media


volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
  client_temp:
