name: examc-dev

services:
  mysql:
    profiles: [ "mysql-dockerized" ]
    ports:
      - ${DB_PORT:-3307}:3306 # used for local client
    volumes:
      - ../deploy/db/dev-seed.sql.gz:/docker-entrypoint-initdb.d/20-seed.sql.gz:ro

  nginx:
    volumes:
      - ../deploy/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
      - /srv/examc/private_media:/private_media:ro
    ports:
      - "8000:80"

  web:
    build:
      target: test
    user: "0"
    environment:
      DEBUG: "1"
      COLLECTSTATIC: "0" # in dev, OK
      PRIVATE_MEDIA_ROOT: /private_media
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - ../app/:/app:z
      - static_volume:/static
      - media_volume:/media
      - /srv/examc/private_media:/private_media   # host -> container (rw)
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload", "--nothreading"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  celery:
    extends:
      service: web
    command: celery -A examc worker --loglevel=INFO --pidfile=/tmp/celery.pid

  celery_beat:
    extends:
      service: web
      command: >
        celery -A examc beat --loglevel=INFO
          --scheduler django_celery_beat.schedulers:DatabaseScheduler
          --pidfile=/tmp/celerybeat.pid
