services:
  mysql:
    extends:
      service: mysql
      file: base.yml

  redis:
    extends:
      service: redis
      file: base.yml

  nginx:
    extends:
      service: nginx
      file: base.yml
    volumes:
      - ../deploy/nginx/nginx.ssl.test.conf:/etc/nginx/nginx.conf:ro
      - ../data/certs/:/etc/nginx/certs:ro  # certs
      - ../data/private_media:/private_media:ro
      - client_temp:/var/cache/nginx/client_temp # see ../deploy/nginx/nginx.ssl.prod.conf:8 for usage
    ports:
      - "127.0.0.1:8080:80"
      #- "8443:443"

  web:
    extends:
      service: web
      file: base.yml
    user: "1000:2770"
    volumes:
      - ../data/private_media:/private_media
      - media_volume:/media:ro # TODO figure out if ro should be put or not here, or be put in every web service
    depends_on:
      mysql:
        condition: service_healthy

  celery:
    extends:
      service: celery
      file: base.yml
    volumes:
      - ../data/private_media:/private_media

  celery_beat:
    extends:
      service: celery_beat
      file: base.yml
    volumes:
      - ../data/private_media:/private_media

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
  client_temp:
