name: examc-prod

services:
  mysql:
    extends:
      service: mysql
      file: base.yml
    profiles: [ "mysql-dockerized" ] # used to run MySQL outside Docker


  redis:
    extends:
      service: redis
      file: base.yml

  nginx:
    extends:
      service: nginx
      file: base.yml
    volumes:
      - ./deploy/nginx/nginx.ssl.prod.conf:/etc/nginx/nginx.conf:ro
      - ./data/certs/:/etc/nginx/certs:ro  # certs
      - ./data/private_media:/private_media:ro
      - client_temp:/var/cache/nginx/client_temp # see ./deploy/nginx/nginx.ssl.prod.conf:8 for usage
    ports:
      - "127.0.0.1:8080:80"
      #- "8443:443"

  fe-artifacts:
    image: ${FE_ARTIFACTS_IMAGE:-ghcr.io/epfl-cepro/examc-fe-artifacts}:${FE_ARTIFACTS_IMAGE_TAG:-stable}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - static_volume:/static
    restart: "no"

  django:
    extends:
      service: django
      file: base.yml
    image: ${DJANGO_IMAGE:-ghcr.io/epfl-cepro/examc-django}:${$DJANGO_IMAGE_TAG:-stable}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data/private_media:/private_media
      - media_volume:/media:ro # TODO figure out if ro should be put or not here, or be put in every django service
    extra_hosts:
      - "host.docker.internal:host-gateway" # Used to access host machine from inside Docker
    depends_on:
      fe-artifacts:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  celery:
    extends:
      service: celery
      file: base.yml
    image: ${DJANGO_IMAGE:-ghcr.io/epfl-cepro/examc-django}:${$DJANGO_IMAGE_TAG:-stable}
    volumes:
      - ./data/private_media:/private_media
    extra_hosts:
      - "host.docker.internal:host-gateway" # Used to access host machine from inside Docker

  celery_beat:
    extends:
      service: celery_beat
      file: base.yml
    image: ${DJANGO_IMAGE:-ghcr.io/epfl-cepro/examc-django}:${$DJANGO_IMAGE_TAG:-staging} # TODO change tag o stable when ready
    volumes:
      - ./data/private_media:/private_media
    extra_hosts:
      - "host.docker.internal:host-gateway" # Used to access host machine from inside Docker

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
  client_temp:
