name: examc-test

services:
  mysql:
    extends:
      service: mysql
      file: base.yml
    env_file:
      - ../.env.test
    ports:
      - ${DB_PORT:-3308}:3306

  redis:
    extends:
      service: redis
      file: base.yml

  nginx:
    extends:
      service: nginx
      file: base.yml
    volumes:
      - ../deploy/nginx/nginx.ssl.test.conf:/etc/nginx/nginx.conf:ro
      # TODO provide an example private_media dir to be integrated in CI/CD
      # - /srv/examc/private_media:/private_media:rod

  web:
    extends:
      service: web
      file: base.yml
    restart: no
    command: ["pytest"]
    build:
      target: test
    env_file:
      - ../.env.test
    environment:
      TESTING_MODE_ENABLED: "1"
      DJANGO_SETTINGS_MODULE: "examc.settings"
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      - media_volume:/media:ro
      - ../app:/app

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
  client_temp: