name: examc-prod

services:
  mysql:
    extends:
      service: mysql
      file: base.yml
    profiles: [ "mysql-dockerized" ] # used to run MySQL outside Docker
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306" # used for local client

  redis:
    extends:
      service: redis
      file: base.yml

  fe-artifacts:
    build:
      context: ../frontend
      target: artifact
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../frontend/app/:/app/frontend:z
      - static_volume:/static
    restart: "no"

  django:
    extends:
      service: django
      file: base.yml
    build:
      context: ../django
      target: test
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../django/app/:/app:z
      - ./data/private_media:/private_media
      - media_volume:/media:ro # TODO figure out if ro should be put or not here, or be put in every django service
    extra_hosts:
      - "host.docker.internal:host-gateway" # Used to access host machine from inside Docker
    depends_on:
      fe-artifacts:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
