"""
Django settings for examc project.

BASE SETTINGS FOR ALL ENV

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 15768000 #6mois
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
# MAX UPLOAD SIZE 10MB (default 2.5MB not enough for review)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760


# Application definition

INSTALLED_APPS = [
    'examc_app.apps.ExamcAppConfig',
    'django.contrib.admindocs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    #'django_tequila',
    #'to_delete_userprofile',
    'sslserver',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap4',
    'simple_history',
    'import_export',
    'django_ckeditor_5',
    'celery',
    'celery_progress',
    'maintenance_mode',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'login_required.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'examc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'docs/build/html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'examc.wsgi.application'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For maintenance set True
MAINTENANCE_MODE = False
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static/'

# Signed files expiration timeout ms
SIGNED_FILES_EXPIRATION_TIMEOUT = 300
SIGNED_FILES_URL = '/protected/'

SCANS_ROOT = BASE_DIR / 'scans/'
#SCANS_URL = '/protected/scans/'

# Marked scans folder
MARKED_SCANS_ROOT = BASE_DIR / 'marked_scans/'
#MARKED_SCANS_URL = '/protected/marked_scans/'

# Autoupload folder
AUTOUPLOAD_ROOT = BASE_DIR / 'autoupload/'
#AUTOUPLOAD_URL = '/autoupload/'

# Export marked files folder tmp
EXPORT_TMP_ROOT = BASE_DIR / 'export_tmp/'
#EXPORT_TMP_URL = '/export_tmp/'
SCALE_PDF_TEMPLATE = BASE_DIR / 'templates/res_and_stats/scale_pdf.html'

# pdf catalogs folder
CATALOG_ROOT = BASE_DIR / 'catalogs/'
#CATALOG_URL = '/catalogs/'

# AMC projects folder
AMC_PROJECTS_ROOT = BASE_DIR / 'amc_projects/'
AMC_PROJECTS_URL = '/amc_projects/'

# AMC config file
AMC_CONFIG_FILE = AMC_PROJECTS_ROOT / 'config/amc_config.xml'

# Documentation folder
DOCUMENTATION_ROOT = BASE_DIR / 'docs/build/html/'
DOCUMENTATION_URL = '/docs/build/html/'

# # Django-tequila specifics
# AUTH_PROFILE_MODULE = "to_delete_userprofile.UserProfile"

# OLD TEQUILA
#AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'django_tequila.django_backend.TequilaBackend',)
# TEQUILA_SERVICE_NAME = "django_tequila_service"
# TEQUILA_SERVER_URL = "https://tequila.epfl.ch"
# TEQUILA_NEW_USER_INACTIVE = False
# TEQUILA_CLEAN_URL = True
# TEQUILA_STRONG_AUTHENTICATION = False
# TEQUILA_ALLOWED_REQUEST_HOSTS = None
# TEQUILA_ALLOW_GUESTS = False
# LOGIN_URL = "/login"
# LOGIN_REDIRECT_URL = "/"
# LOGOUT_URL = "/"
# LOGIN_REDIRECT_IF_NOT_ALLOWED = "/not_allowed"
# LOGIN_REDIRECT_TEXT_IF_NOT_ALLOWED = "Not allowed : please contact your admin"

# NEW ENTRA ID
####################################################
# Authentication settings
####################################################
AUTHENTICATION_BACKENDS = ("mozilla_django_oidc.auth.OIDCAuthenticationBackend","django.contrib.auth.backends.ModelBackend")
TENANT_ID = os.environ["TENANT_ID"]

OIDC_RP_CLIENT_ID = os.environ["OIDC_RP_CLIENT_ID"]
OIDC_RP_CLIENT_SECRET = os.environ["OIDC_RP_CLIENT_SECRET"]

AUTH_DOMAIN = f"https://login.microsoftonline.com/{TENANT_ID}"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/token"
OIDC_OP_JWKS_ENDPOINT = f"{AUTH_DOMAIN}/discovery/v2.0/keys"
OIDC_OP_USER_ENDPOINT = "https://graph.microsoft.com/oidc/userinfo"
OIDC_RP_SIGN_ALGO = "RS256"
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Only use this setting if you want to store the access token in the session
# To use access token to call API
#OIDC_STORE_ACCESS_TOKEN = True

LOGIN_REQUIRED_IGNORE_PATHS = [
    r'/login_form/',
    r'/$',
    r'/$',
    r'^/oidc/.*$',  # All OIDC-related URLs
    r'^/admin/.*$',
    r'^/admin$',
    r'^/static/.*$',
    r'^/media/.*$',

]
LOGIN_REQUIRED_REDIRECT_FIELD_NAME = 'next_url'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.epfl.ch'  # SMTP server host
EMAIL_PORT = 587  # SMTP server port (587 for TLS, 465 for SSL)
EMAIL_USE_TLS = True  # True for TLS, False for SSL
EMAIL_HOST_USER = 'noreply-cepro-exams'  # SMTP server username
EMAIL_HOST_PASSWORD = 'NP!Cpr0_X@2022'  # SMTP server password
EMAIL_USE_SSL = False  # Set to True if using SSL
DEFAULT_FROM_EMAIL = 'noreply-cepro-exams@epfl.ch'  # Default sender email address

# Pandoc filters
PANDOC_UTILS_DIR = BASE_DIR / 'examc_app/utils/pandoc'

# Rooms plans pathes
ROOMS_PLANS_ROOT = BASE_DIR / 'rooms_plans'
ROOMS_PLANS_URL = '/rooms_plans/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django_tequila': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

## Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ALWAYS_EAGER  = True # True to debug task
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60

## CKEDITOR Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'blockToolbar': [
            'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'fontSize', 'fontColor', 'bold', 'italic', 'underline', 'strikethrough',
                    'code','subscript', 'superscript','|','bulletedList', 'numberedList', '|', 'alignment', 'outdent', 'indent',
                    '|', 'insertImage','insertTable', '|','codeBlock', 'sourceEditing'],
        'image': {
            'toolbar': ['imageStyle:alignLeft','imageStyle:alignRight', 'imageStyle:alignCenter'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'alignment': {
            'options': [ 'left', 'right' ]
        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5', 'class': 'ck-heading_heading5' }
            ]
        },
        'codeBlock':{
            'languages': [
                { 'language': 'latex', 'label': 'LaTeX' }, # The default 'language'.
            ]
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
