"""
Django settings for examc project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['vpaavpvm0011.xaas.epfl.ch']

DATABASES = {
    'default': {
        'NAME': 'examc',
        'ENGINE': 'django.db.backends.mysql',
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASS'],
        'OPTIONS': {
            'autocommit': True,
        },
    }
}

# Private storage server
PRIVATE_STORAGE_SERVER = "apache"

